#file: noinspection YAMLSchemaValidation
---
- name: Configure Deploy
  hosts: cert_emp_deploy
  become: yes

  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Ensure git package is present
      apt:
        name: git
        state: present

    - name: Create workdir
      command: "mkdir /home/ubuntu/my_app"

    - name: Example clone repository
      git:
        repo: https://github.com/vinayakrj/java-war-project.git
        dest: /home/ubuntu/my_app

    - name: Move workdir
      become: yes
      shell: "cd /home/ubuntu/my_app && mvn package"

    - name: Copy war-file in master
      fetch:
        src: /home/ubuntu/my_app/target/my-app.war
        dest: /tmp/
        flat: yes

- name: Configure Prod
  hosts: cert_emp_prod
  become: yes

  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Copy my-app.war
      copy:
        src: /tmp/my-app.war
        dest: /usr/local/tomcat/webapps/my-app.war
